spring:
  data:
    redis:
      database: 1
      host: 8.134.48.80
      port: 6379
      password: satan@redis
      #timeout: 6000ms  # 连接超时时长（毫秒）
  datasource:
    dynamic:
      hikari: # Hikari 连接池全局配置
        connection-timeout: 30000     # 等待连接池分配链接的最大时长（毫秒），超过这个时长还没有可用的连接则发生 SQLException，默认：30 秒
        minimum-idle: 2               # 最小空闲连接数
        maximum-pool-size: 10         # 最大连接数
        idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10 分钟
        max-lifetime: 1800000         # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认： 30 分钟
        connection-test-query: SELECT 1
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://satan:3306/be-water?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
          username: root
          password: satan@mysql


logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wx.mp: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    useRedis: false
    redisConfig:
      host: satan
      port: 6379
      password: satan@redis
    configs:
      - appId: wxac4aff5e8fd034f6 # 第一个公众号的appid
        secret: da1e528b223f6cfbfb523f4cd1a448f4 # 公众号的appsecret
        token:   # 接口配置里的Token值
        aesKey:   # 接口配置里的EncodingAESKey值
